### ISSUE TITLE
upmパッケージとして利用できない

### ISSUE THREAD

**Issue by a1678991** [anatawa12/unity-gist-pack#10]
READMEに従って以下のようにupmパッケージとしてインストールすると、ほぼすべての機能が利用できない状態になります。
`"com.anatawa12.gists": "https://github.com/anatawa12/unity-gist-pack.git"`
ほとんどのgistにmetaファイルが含まれていないためUnityが新たにmetaファイルを生成しようとしますが、upmパッケージは変更不可能なのでファイル作成が必ず失敗します。

metaファイルが存在しないアセットはUnityに無視されるので、gistにmetaもアップロードされているAndroidOnlyCheck以外のすべてのスクリプトが利用できない状態になります。

![image](https://github.com/anatawa12/unity-gist-pack/assets/7441512/adf96cef-bd79-45a0-9a7b-40242eef7df9)

![image](https://github.com/anatawa12/unity-gist-pack/assets/7441512/6ed57c33-a7b8-4e18-960f-0ffac4a9b6cd)

**Comment by anatawa12** [comment]
なるほどです

gist packで結局採用したgistの切り替え方法もPackages以下の変更に依存してるのでそもそもgit upmの対応と謳ってること自体が間違いな気もしてきました。確認します

**Comment by anatawa12** [comment]
ドキュメントからupm対応を消す形で対応しました。
