### ISSUE TITLE
0.10.1がバグっています

### ISSUE THREAD

**Issue by Narazaka** [anatawa12/unity-gist-pack#14]
各metaファイルが`guid:`のみのファイルになっています

The .meta file Packages/com.anatawa12.gists/Scripts/CompilationLogWindow/CompilationLogWindow.cs.meta does not have a valid GUID and its corresponding Asset file will be ignored. If this file is not malformed, please add a GUID, or delete the .meta file and it will be recreated correctly

**Comment by anatawa12** [comment]
自分環境だと何故かエラーに成ってなかった...修正します

**Comment by anatawa12** [comment]
e19234d5560db073e5a660899b4078930f79d5aa v0.10.2で修正しました
