### ISSUE TITLE
[featreq] "Build & Upload without pre-check"ボタン

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/unity-gist-pack#15]
Android platform向けのビルドを行いたい場合に、NDMF環境と著しく相性が悪いので、build&uploadのPublic APIを叩くだけのgistを追加してもらえると非常に助かります…

UIとか面倒そうなので、アバターを選択して右クリックの項目からで良いかな?と思っています。

Related:
- https://github.com/bdunderscore/ndmf/issues/88
- https://feedback.vrchat.com/sdk-bug-reports/p/feedback-please-provide-way-for-official-control-panel-to-avoid-pre-check

**Comment by anatawa12** [comment]
gist packは作ったものの置き場なのでgithub issuesのfeat reqを受け付けるつもりはないです。

**Comment by Sayamame-beans** [comment]
ok
