### ISSUE TITLE
AAO 1.8.0 で Clone された Material Variant の Texture Memory が Actual Performance Window で計上されない 

### ISSUE THREAD

**Issue by nekobako** [anatawa12/unity-gist-pack#21]
AAO 1.8.0 からアバターのマテリアルを Clone するようになったようですが、Clone されたのが Material Variant だった場合 Texture Memory が Actual Performance Window で計上されないようです。

以下は全てのマテリアルが Material Variant で構成されたアバターで、AAO のバージョン違いで試してみた結果です。
部分的に Material Variant でなくするとその分は計上されます。

AAO 1.7.13
![image](https://github.com/user-attachments/assets/5b451885-ae1c-4413-81d1-715bf2830beb)

AAO 1.8.0-beta.7
![image](https://github.com/user-attachments/assets/caaab9cf-eb3d-471f-b0f6-a68d109a3406)

**Comment by anatawa12** [comment]
要確認ではあるけどぶいちゃ側の計算ロジックに乗ってるのでSDK側のバグな気もする？

**Comment by nekobako** [comment]
Unity のバグの可能性もあるかも…？

Manual Bake では大丈夫なことと、AAO で DeepClone の Instantiate の後に
```
if (obj is Material mat)
{
    mat.parent = null;
}
```
を入れて flatten すればプレイモードでも大丈夫なことは確認しました。

**Comment by anatawa12** [comment]
なるほど

AssetBundleのサイズ的に差があまりないならaao内部でflattenしてもいいな

(使ってないプロパティが残ったりは正直ありそうだけど比較ができてない)

**Comment by nekobako** [comment]
Unity のバグっぽかったのでバグレポートを出しておきました。
```cs
public class Test : MonoBehaviour
{
    [SerializeField]
    private Material m_MaterialVariant = null;

    [ContextMenu("LogTexturePropertyNameIDs")]
    private void LogTexturePropertyNameIDs()
    {
        var ids = new List<int>();
        m_MaterialVariant.GetTexturePropertyNameIDs(ids);
        Debug.Log($"Variant: {ids.Count}");

        var instantiated0 = Instantiate(m_MaterialVariant);
        instantiated0.GetTexturePropertyNameIDs(ids);
        Debug.Log($"Instantiated Variant: {ids.Count}");

        instantiated0.parent = null;
        instantiated0.GetTexturePropertyNameIDs(ids);
        Debug.Log($"Flattened Instantiated Variant: {ids.Count}");
    }
}
```
![image](https://github.com/user-attachments/assets/06f9aceb-b280-4b75-8604-e00204022bf8)

**Comment by nekobako** [comment]
Issue Tracker に載りました。

https://issuetracker.unity3d.com/issues/an-empty-list-is-incorrectly-returned-for-material-variant-when-using-material-dot-gettexturepropertynameids

**Comment by nekobako** [comment]
直ってました！　ありがとうございます。

**Comment by anatawa12** [comment]
じゃあ一旦 Close します
