### ISSUE TITLE
少なくとも0.8.0が入っていたプロジェクトに0.9.0をインポートするとDynamicBoneのGUIDが変化する

### ISSUE THREAD

**Issue by Narazaka** [anatawa12/unity-gist-pack#7]
0.9.0インポートすると

- Assets/DynamicBone/Scripts/DynamicBone.cs.meta
- Assets/DynamicBone/Scripts/DynamicBoneCollider.cs.meta

の`guid:`が変化する。

これはgit checkout等で一時的に元に戻してもimportが走ったら再度変化する。

FakeDynamicBoneComponentsのGUIDも変化しているのでなにかその辺のインポートが変わった？

0.8.0に戻してgit reset --hardなどをすると変化しなくなる。

**Comment by anatawa12** [comment]
0.9.1で修正されたはずです
