### ISSUE TITLE
com.vrchat.udonsharp package for Version Define Not Available in SDK 3.4.0

### ISSUE THREAD

**Issue by momo-the-monster** [anatawa12/unity-gist-pack#8]
Hello - _you_ are that author I mentioned in the latest VRChat developer update about merging the ClientSim and UdonSharp packages, who uses a Version Define that will no longer be available. I've highlighted it below.

https://github.com/anatawa12/unity-gist-pack/blob/a69a96373aa96b29b89710d21d3f1dc7e7e5c028/Selector/com.anatawa12.gists.selector.asmdef#L32

**Comment by anatawa12** [comment]
Thank you for rising issue!
I'm planned to add another version defines with VRCSDK worlds >= 3.4.0 < 4.0.0 for UDON_SHARP symbol but if VRCSDK is going to remove UdonSharp in 3.x.x (especially for asmdef and UdonSharpAssemblyDefinition), I'll use more stricter version range like VRCSDK worlds >= 3.4.0 < 3.5.0.
How do you think which is better?

**Comment by momo-the-monster** [comment]
You can use `>= 3.4.0 < 4.0.0`. The next update after 3.4.0 will likely be 4.0.0 with Unity 2022 support.
